### ISSUE TITLE
Enhancement request: Allow usage of dots/numbers to differenciate entries

### ISSUE THREAD

**Issue by OneComputerGuy** [basyura/inkdrop-sidetoc#13]
I've been using the plugin for quite a while now and, although out of the box it works perfectly, I sometimes find it hard to differentiate between entries. Adding a small dot or mark at the end of each entry will help separate items from the list.

**Comment by basyura** [comment]
Thanks.

You can change style by styles.less.

https://docs.inkdrop.app/manual/style-tweaks

> If you want to apply quick-and-dirty personal styling changes without creating an entire theme that you intend to 
 publish, you can add styles to the styles.less file in your data directory. It does not exist by default.

sample

```css
.sidetoc-pane li {
  list-style: inside;
}
```
or

```css
.sidetoc-pane li::after {
  content: ".";
}
```

**Comment by KINGSABRI** [comment]
Good idea. 
I tried this 

```
nano ~/Library/Application\ Support/inkdrop/packages/sidetoc/styles/sidetoc.less
```

```css
.sidetoc-pane li::before {
  content: "- ";
}
```
